### PR TITLE
Changing to lower case

### PR DESCRIPTION
**Pull request by ThomasLandauer**
AJAX is spelled inconsistently throughout the course. Can you do a full-text search for "AJAX"?

### CODE REVIEW

**Review by bocharsky-bw — APPROVED** [review]
Hm, IMO it's controversial https://en.wikipedia.org/wiki/Ajax_(programming)

But looks like most cases are written as "Ajax" so I'm fine with this

**Comment by bocharsky-bw** [comment]
P.S. If you see more spots where it's AJAX - please, let's fix it in this PR

Tip: to check all spots you can use `git grep AJAX`

**Comment by weaverryan** [comment]
`Ajax` looks better on my eyes, and that's coming from the person who originally wrote as `AJAX` :p

**Review by bocharsky-bw — APPROVED** [review]
Thanks!

**Pull request merged**
